name: t21-tue-simpeg

channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets>=0.6.0
  - mkl
  - simpeg
  - pyvista
  - pip
  - pip:
    - git+https://github.com/geoscixyz/geosci-labs